/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.ServicioControlador;
import dao.*;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import modelo.*;
/**
 *
 * @author BrayanOcampo
 */
public class VentanaPrincipal extends javax.swing.JFrame {
private ServicioControlador controlador;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(ServicioControlador controlador) {
        this.controlador = controlador;
        initComponents();
        
        //Opciones comboBox
        comboEstado.removeAllItems(); // Limpia los items viejos como "Item 1"
        comboEstado.addItem("Pendiente");
        comboEstado.addItem("En curso");
        comboEstado.addItem("Finalizado");
        
        //Tabla de servicio
        setTitle("Gestion de servicios tecnicos");
        DefaultTableModel modelo = new DefaultTableModel(
        new String[] { "ID", "Cliente", "Problema", "Estado", "Técnico" }, 0);
        modeloTecnico.setModel(modelo); 
        // Tabla de ver todos los servicios
        tablaServicios.setModel(modelo);
    }

    // Metodo que recarga la tabla con todos los servicios actuales
    private void actualizarTablaServicios() {
    // Obtener la lista de servicios desde el controlador
        List<Servicio> lista = controlador.listarTodos();
        // Obtener el modelo actual de la tabla
        DefaultTableModel modelo = (DefaultTableModel) tablaServicios.getModel();
        // Limpiar todas las filas anteriores
        modelo.setRowCount(0);

        // Recorrer la lista y agregar cada servicio como fila
        for (Servicio s : lista) {
            modelo.addRow(new Object[] {
                s.getId(),                         // ID del servicio
                s.getCliente(),                    // Nombre del cliente
                s.getTipoProblema(),               // Tipo de problema
                s.getEstado(),                     // Estado actual
                // Mostrar ID del tecnico o "Sin asignar" si no tiene
                s.getIdTecnicoAsignado() != -1 ? s.getIdTecnicoAsignado() : "Sin asignar"
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelRegistro = new javax.swing.JPanel();
        txtCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProblema = new javax.swing.JTextField();
        bttRegistrar = new javax.swing.JButton();
        panelAsignar = new javax.swing.JPanel();
        txtIdServicio = new javax.swing.JTextField();
        txtIdTecnico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bttAsignar = new javax.swing.JButton();
        panelCambiar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtIdServicioEstado = new javax.swing.JTextField();
        bttCambiarEstado = new javax.swing.JButton();
        panelEliminar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtidEliminar = new javax.swing.JTextField();
        bttEliminar = new javax.swing.JButton();
        panelServicio = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtIdTecnicoBuscar = new javax.swing.JTextField();
        bttConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        modeloTecnico = new javax.swing.JTable();
        panelVerServicios = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaServicios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cliente:");

        jLabel2.setText("Descripcion del problema:");

        bttRegistrar.setText("Registrar");
        bttRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addGap(58, 58, 58)
                        .addComponent(txtProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(bttRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(bttRegistrar)
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("Registrar", panelRegistro);

        jLabel3.setText("ID Servicio:");

        jLabel4.setText("ID Tecnico:");

        bttAsignar.setText("Asignar");
        bttAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAsignarLayout = new javax.swing.GroupLayout(panelAsignar);
        panelAsignar.setLayout(panelAsignarLayout);
        panelAsignarLayout.setHorizontalGroup(
            panelAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsignarLayout.createSequentialGroup()
                .addGroup(panelAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAsignarLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(panelAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(panelAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelAsignarLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(bttAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        panelAsignarLayout.setVerticalGroup(
            panelAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsignarLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(panelAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(panelAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(bttAsignar)
                .addGap(70, 70, 70))
        );

        jTabbedPane1.addTab("Asignar", panelAsignar);

        jLabel5.setText("ID Servicio: ");

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoActionPerformed(evt);
            }
        });

        jLabel6.setText("Estado:");

        bttCambiarEstado.setText("Cambiar estado");
        bttCambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCambiarEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCambiarLayout = new javax.swing.GroupLayout(panelCambiar);
        panelCambiar.setLayout(panelCambiarLayout);
        panelCambiarLayout.setHorizontalGroup(
            panelCambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambiarLayout.createSequentialGroup()
                .addGroup(panelCambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCambiarLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(panelCambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCambiarLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdServicioEstado))
                            .addGroup(panelCambiarLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelCambiarLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(bttCambiarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        panelCambiarLayout.setVerticalGroup(
            panelCambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambiarLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panelCambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdServicioEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelCambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(bttCambiarEstado)
                .addGap(82, 82, 82))
        );

        jTabbedPane1.addTab("Cambiar", panelCambiar);

        jLabel7.setText("ID Servicio: ");

        bttEliminar.setText(" Eliminar servicio");
        bttEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEliminarLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtidEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEliminarLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(bttEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtidEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(bttEliminar)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", panelEliminar);

        jLabel8.setText("ID Tecnico:");

        bttConsultar.setText("Consultar");
        bttConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttConsultarActionPerformed(evt);
            }
        });

        modeloTecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(modeloTecnico);

        javax.swing.GroupLayout panelServicioLayout = new javax.swing.GroupLayout(panelServicio);
        panelServicio.setLayout(panelServicioLayout);
        panelServicioLayout.setHorizontalGroup(
            panelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServicioLayout.createSequentialGroup()
                .addGroup(panelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelServicioLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdTecnicoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelServicioLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(bttConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );
        panelServicioLayout.setVerticalGroup(
            panelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServicioLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panelServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdTecnicoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addComponent(bttConsultar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Servicio", panelServicio);

        tablaServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaServicios);

        javax.swing.GroupLayout panelVerServiciosLayout = new javax.swing.GroupLayout(panelVerServicios);
        panelVerServicios.setLayout(panelVerServiciosLayout);
        panelVerServiciosLayout.setHorizontalGroup(
            panelVerServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelVerServiciosLayout.setVerticalGroup(
            panelVerServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerServiciosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver todos los servicios", panelVerServicios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRegistrarActionPerformed
        // TODO add your handling code here:
         // Obtener los valores ingresados por el usuario
        String cliente = txtCliente.getText();
        String problema = txtProblema.getText();
        // Verificar que los campos no esten vacios
        if (cliente.isEmpty() || problema.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.");
            return; // Detiene la ejecucion si falta informacion
    }

    // Registrar el servicio usando el controlador
    controlador.registrarServicio(cliente, problema);
    // Mostrar mensaje de confirmacion
    JOptionPane.showMessageDialog(null, "Servicio registrado correctamente.");  
    // Recargar la tabla con los servicios actualizados
    actualizarTablaServicios();
    
    // Limpiar los campos de texto
    txtCliente.setText(null);
    txtProblema.setText(null);
    }//GEN-LAST:event_bttRegistrarActionPerformed

    private void bttAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAsignarActionPerformed
        // TODO add your handling code here:
        try {
            // Obtener los IDs ingresados por el usuario y convertirlos a enteros
            int idServicio = Integer.parseInt(txtIdServicio.getText());
            int idTecnico = Integer.parseInt(txtIdTecnico.getText());
            // Asignar el tecnico al servicio usando el controlador
            controlador.asignarTecnico(idServicio, idTecnico);
            // Mostrar mensaje de confirmacion
            JOptionPane.showMessageDialog(null, "Tecnico asignado.");
            // Actualizar la tabla con los cambios
            actualizarTablaServicios();

    // Limpiar los campos de texto
    txtIdServicio.setText("");
    txtIdTecnico.setText("");
    
        } catch (NumberFormatException ex) {
            // Mostrar mensaje si los IDs no son numeros validos
            JOptionPane.showMessageDialog(null, "IDs deben ser numericos.");
}
    }//GEN-LAST:event_bttAsignarActionPerformed

    private void bttCambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCambiarEstadoActionPerformed
        // TODO add your handling code here:
        try {
            // Obtener el ID del servicio desde el campo de texto
            int idServicio = Integer.parseInt(txtIdServicioEstado.getText());
            // Obtener el estado seleccionado del combo
            String estado = (String) comboEstado.getSelectedItem();
            // Cambiar el estado del servicio usando el controlador
            controlador.cambiarEstado(idServicio, estado);
            // Mostrar mensaje de confirmacion
            JOptionPane.showMessageDialog(null, "Estado actualizado.");
            // Actualizar la tabla con los cambios
            actualizarTablaServicios();

        } catch (NumberFormatException ex) {
            // Mostrar mensaje si el ID no es un numero valido
            JOptionPane.showMessageDialog(null, "ID invalido.");
}

    }//GEN-LAST:event_bttCambiarEstadoActionPerformed

    private void bttEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEliminarActionPerformed
        // TODO add your handling code here:
         try {
            // Obtener el ID del servicio a eliminar desde el campo de texto
            int id = Integer.parseInt(txtidEliminar.getText());
            // Intentar eliminar el servicio si esta finalizado
            controlador.eliminarFinalizado(id);
            // Mostrar mensaje de confirmacion
            JOptionPane.showMessageDialog(null, "Eliminado si estaba finalizado.");
            // Actualizar la tabla para reflejar los cambios
            actualizarTablaServicios();
            // Limpiar el campo de texto
            txtidEliminar.setText(null);

        } catch (NumberFormatException ex) {
            // Mostrar mensaje si el ID no es un numero valido
            JOptionPane.showMessageDialog(null, "ID invalido.");
}

    }//GEN-LAST:event_bttEliminarActionPerformed

    private void bttConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttConsultarActionPerformed
        // TODO add your handling code here:
          try {
            // Obtener el ID del tecnico desde el campo de texto
            int idTecnico = Integer.parseInt(txtIdTecnicoBuscar.getText());
            // Consultar los servicios asignados a ese tecnico
            List<Servicio> lista = controlador.consultarPorTecnico(idTecnico);
            // Obtener el modelo de la tabla que muestra los resultados
            DefaultTableModel modelo = (DefaultTableModel) modeloTecnico.getModel();
            // Limpiar las filas anteriores de la tabla
            modelo.setRowCount(0);

        // Agregar cada servicio encontrado como una nueva fila en la tabla
                for (Servicio s : lista) {
                    modelo.addRow(new Object[] {
                    s.getId(),               // ID del servicio
                    s.getCliente(),          // Cliente
                    s.getTipoProblema(),     // Tipo de problema
                    s.getEstado(),           // Estado actual
                    s.getIdTecnicoAsignado() // ID del tecnico asignado
        });
    }

            } catch (NumberFormatException ex) {
                 // Mostrar mensaje si el ID ingresado no es numerico
                JOptionPane.showMessageDialog(null, "El ID debe ser numerico.");
}


    }//GEN-LAST:event_bttConsultarActionPerformed

    private void comboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ServicioDAO dao = new ServicioDAOImpl();
                ServicioControlador controlador = new ServicioControlador(dao);
                new VentanaPrincipal(controlador).setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAsignar;
    private javax.swing.JButton bttCambiarEstado;
    private javax.swing.JButton bttConsultar;
    private javax.swing.JButton bttEliminar;
    private javax.swing.JButton bttRegistrar;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable modeloTecnico;
    private javax.swing.JPanel panelAsignar;
    private javax.swing.JPanel panelCambiar;
    private javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPanel panelServicio;
    private javax.swing.JPanel panelVerServicios;
    private javax.swing.JTable tablaServicios;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtIdServicio;
    private javax.swing.JTextField txtIdServicioEstado;
    private javax.swing.JTextField txtIdTecnico;
    private javax.swing.JTextField txtIdTecnicoBuscar;
    private javax.swing.JTextField txtProblema;
    private javax.swing.JTextField txtidEliminar;
    // End of variables declaration//GEN-END:variables
}
